version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_TEMPO=true
      - VITE_API_URL=http://localhost:8000/api
    command: npm run dev -- --host
    depends_on:
      - api
    profiles: ["dev"]  # This service belongs to the "dev" profile


  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certbot-ssl:/var/www/certbot  # For temporary ACME challenges
      - /etc/letsencrypt:/etc/letsencrypt  # For SSL certificates
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://api:8000/api  # Direct access to API service within Docker network
    depends_on:
      - api
    profiles: ["prod"]  # This service belongs to the "prod" profile

  # API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./api/staticfiles:/app/staticfiles
    environment:
      - DJANGO_DEBUG=true
      - DJANGO_SETTINGS_MODULE=realestate.settings
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    profiles: ["dev", "prod"]  # This service belongs to both profiles

  # Database service
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realestatedb
    profiles: ["dev", "prod"]  # This service belongs to both profiles

#volumes:
  #postgres_data:

networks:
  default:
    driver: bridge
