# Generated by Django 4.2.7 on 2025-03-07 20:27

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default=0, upload_to=properties.models.get_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
