# Generated by Django 4.2.7 on 2025-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_price_remove_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='beds',
            new_name='rooms',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Terrain', 'Terrain'), ('Appartement', 'Appartement'), ('Villa', 'Villa'), ('Maison', 'Maison'), ('Résidence', 'Résidence')], max_length=50),
        ),
    ]
